# 공통

server:
  port: 8080

# 프로파일 지정 없으면 디폴트로 local 사용
spring:
  profiles:
    active: local

---

# 로컬용
spring:
  config:
    activate:
      on-profile: local
api-gateway-url: http://localhost:8081

---
